services:
  postgres:
    image: postgres:16-alpine
    container_name: edusphere-postgres
    environment:
      POSTGRES_USER: edusphere
      POSTGRES_PASSWORD: edusphere_dev
      POSTGRES_DB: edusphere
    ports:
      - '5439:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U edusphere']
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: edusphere-redis
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: edusphere-minio
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: edusphere
      MINIO_ROOT_PASSWORD: edusphere_dev
    ports:
      - '9002:9000'
      - '9003:9001'
    volumes:
      - miniodata:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: edusphere-mailpit
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  pgdata:
  miniodata:
